[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "9.6.7"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[dev]
  command = "npm run dev"
  port = 3000
  publish = ".next"

# Configure automatic deploys to specific GitHub branches
[context.production]
  command = "npm run build"
  
[context.deploy-preview]
  command = "npm run build" 